// src/utils/dataFreshness.ts
// Cheap "is my already-loaded data still current" checks built on top of DataLoader's manifest
// (public/data/manifest.json, a relPath -> content-hash map regenerated by
// scripts/generate-data-manifest.mjs on every build/dev start). The scenario this guards
// against: someone leaves the SPA open in a tab (or keeps building a rotation) while the site's
// data files get updated on the server -- DataLoader's own in-memory cache (cache.mechanics,
// characterResults) would otherwise happily keep serving whatever it fetched at page-load time
// for the rest of that session, with no way to notice a change short of a hard refresh.
//
// A mechanic/weapon/set/echo/generic entity that changed upstream is safe to silently evict (the
// next thing that needs it just transparently re-fetches) UNLESS the user has local unsaved
// edits to it in the Mechanics Builder (useBuilderStore.hasChanges) -- silently discarding those
// out from under them would be a real loss, so that case is instead surfaced through
// useFreshnessConflictStore for a conflict dialog to resolve. Rankings' character_results files
// have no Builder-editable counterpart, so they're always just silently evicted.
import { create } from 'zustand';
import { DataLoader } from './DataLoader';
import { useBuilderStore } from '../store/useBuilderStore';
import type { TeamSlot } from '../types';

export interface FreshnessItem {
  folder: string;
  itemName: string;
}

interface FreshnessConflictState {
  conflicts: FreshnessItem[];
  raise: (items: FreshnessItem[]) => void;
  // Dismiss without touching anything -- the stale (but locally-edited) data stays exactly as
  // it is, edits and all, until the user does something else that re-triggers a check.
  keep: () => void;
  // Drops the listed items' local edit logs and evicts them from DataLoader so the next load
  // picks up the fresh server version. Reloads the Mechanics Builder's currently-open entity
  // first if it was one of them, so the editor doesn't sit on now-cleared state.
  discard: () => Promise<void>;
}

// A small standalone store (not persisted -- a conflict is a live, session-only prompt) purely
// to drive the one conflict dialog mounted at the App root; any freshness check anywhere in the
// app can push into it without threading the dialog through props.
export const useFreshnessConflictStore = create<FreshnessConflictState>((set, get) => ({
  conflicts: [],

  raise: items => set(state => {
    const seen = new Set(state.conflicts.map(c => `${c.folder}/${c.itemName}`));
    const merged = [...state.conflicts];
    items.forEach(item => {
      const key = `${item.folder}/${item.itemName}`;
      if (!seen.has(key)) { seen.add(key); merged.push(item); }
    });
    return { conflicts: merged };
  }),

  keep: () => set({ conflicts: [] }),

  discard: async () => {
    const { conflicts } = get();
    conflicts.forEach(({ folder, itemName }) => {
      useBuilderStore.getState().discardChanges(itemName);
      DataLoader.clearMechanicCache(folder, itemName);
    });
    set({ conflicts: [] });

    const { activeChar, activeFolder, activeRarity, setActiveChar } = useBuilderStore.getState();
    if (activeChar && conflicts.some(c => c.itemName === activeChar)) {
      await setActiveChar(activeChar, activeFolder, activeRarity);
    }
  }
}));

// Shared by every check below: compares each candidate's recorded loadedHash against a fresh
// manifest, silently evicting anything changed-and-unedited (returned, so a caller that also
// owns a *separate* cache of the same data -- the calc worker's own DataLoader instance, see
// calc.worker.ts -- can mirror the same eviction there), and collecting anything
// changed-but-locally-edited into one raise() call.
async function checkItems(items: FreshnessItem[]): Promise<FreshnessItem[]> {
  if (items.length === 0) return [];
  const manifest = await DataLoader.refreshManifest();
  const conflicts: FreshnessItem[] = [];
  const evicted: FreshnessItem[] = [];

  for (const { folder, itemName } of items) {
    const cacheKey = `${folder}/${itemName.replace(/\s+/g, '_')}`;
    if (!DataLoader.cache.mechanics.has(cacheKey)) continue; // never loaded -- nothing to check

    const relPath = DataLoader.mechanicPath(folder, itemName);
    const latestHash = manifest[relPath];
    if (!latestHash) continue; // manifest doesn't know this path (e.g. it 404'd) -- nothing to compare against

    const knownHash = DataLoader.loadedHashes[relPath];
    if (!knownHash) {
      // Loaded once before a manifest was available to record a baseline against (e.g. its
      // very first fetch raced ahead of the first successful refreshManifest) -- adopt the
      // current hash as that baseline now instead of leaving this path permanently unable to
      // ever be checked again for the rest of the session.
      DataLoader.loadedHashes[relPath] = latestHash;
      continue;
    }
    if (knownHash === latestHash) continue; // unchanged

    const builderItemName = folder === 'generic' ? 'Generic' : itemName;
    if (useBuilderStore.getState().hasChanges(builderItemName)) {
      conflicts.push({ folder, itemName });
    } else {
      // Evict then immediately re-fetch on the main thread too -- otherwise this entity's
      // mechanicsDB entries stay cleared until something else happens to call loadMechanic
      // again, which would blank out the Rotation Row's Action dropdown (it can't resolve a
      // label for a row it no longer has mechanic data for) for no reason a user would
      // understand.
      DataLoader.clearMechanicCache(folder, itemName);
      await DataLoader.loadMechanic(folder, itemName);
      evicted.push({ folder, itemName });
    }
  }

  if (conflicts.length > 0) useFreshnessConflictStore.getState().raise(conflicts);
  return evicted;
}

// Every mechanic currently loaded for a team's characters/weapons/sets/echoes -- the "any loaded
// jsons for this page" scope for the Rotation Calculator's tab-focus and pre-Calculate checks.
// Deliberately excludes 'generic'/System mechanics: DataLoader.clearMechanicCache's own
// itemName === 'Generic' special case (see its own comment) only matches the capitalized name
// the Mechanics Builder uses, while initDatabases() loads it lowercase -- same pre-existing
// casing mismatch builderOverridePayload.ts's own eviction already routes around, so this does
// too rather than risk leaving System mechanics missing instead of just occasionally stale.
// Returns whichever were evicted (see checkItems) so a Calculate press can also tell the calc
// worker's own separate DataLoader instance to drop the same entries -- otherwise the worker
// would keep simulating against whatever it happened to fetch at its own first use, unaffected
// by anything evicted here on the main thread.
export async function checkTeamFreshness(team: TeamSlot[]): Promise<FreshnessItem[]> {
  const items: FreshnessItem[] = [];
  team.forEach(slot => {
    if (slot.character) items.push({ folder: 'characters', itemName: slot.character });
    if (slot.weapon) items.push({ folder: 'weapons', itemName: slot.weapon });
    if (slot.mainSet) items.push({ folder: 'sets', itemName: slot.mainSet });
    if (slot.subSet) items.push({ folder: 'sets', itemName: slot.subSet });
    if (slot.mainEcho) items.push({ folder: 'echoes', itemName: slot.mainEcho });
  });
  return checkItems(items);
}

// Checked right before the Mechanics Builder opens one specific entity for editing.
export async function checkBuilderItemFreshness(folder: string, itemName: string): Promise<void> {
  await checkItems([{ folder, itemName }]);
}

// Rankings results files have no Builder-editable counterpart, so there's never a "local edits"
// conflict for them -- anything changed is just silently evicted from
// DataLoader.characterResults so the next loadCharacterResults() call re-fetches it. Returns
// whether anything was evicted, so the caller (useRankingsStore.load) knows to force a re-load
// even if its own status already says 'ready'.
export async function checkResultsFreshness(): Promise<boolean> {
  const manifest = await DataLoader.refreshManifest();
  const indexPath = 'character_results/index.json';

  const indexKnown = DataLoader.loadedHashes[indexPath];
  const indexLatest = manifest[indexPath];
  if (indexKnown && indexLatest && indexKnown !== indexLatest) {
    // The manifest of *which* results exist changed (an entry added/removed/renamed) -- wipe
    // everything rather than trying to diff a file list, no need to also check individual files.
    DataLoader.characterResults = {};
    return true;
  }

  let changed = false;
  Object.keys(DataLoader.characterResults).forEach(filename => {
    const relPath = `character_results/${filename}`;
    const knownHash = DataLoader.loadedHashes[relPath];
    const latestHash = manifest[relPath];
    if (knownHash && latestHash && knownHash !== latestHash) {
      delete DataLoader.characterResults[filename];
      changed = true;
    }
  });
  return changed;
}
