import { CommonUtils } from './Common';
import type { CharacterData, WeaponData, MechanicNode, TeamSlot } from '../types/index';
import type { RotationResults } from '../types/results';

export interface CharacterResultData {
  rotation: any[];
  team: TeamSlot[];
  settings: { startEnergy?: boolean; startConcerto?: boolean; endingRotationEnabled?: boolean; endRotationStartsEarlier?: boolean };
  rotationType: 'linear' | 'quickswap' | null;
  // Present when the file was produced by History's "Save Results" -- lets the Rankings loader
  // skip re-running the calc worker for this entry entirely. Absent for a plain Export Rotation
  // file, which only ever has rotation/team/settings. dmgOverTimeSeries is deliberately left
  // out of what Save Results writes (nothing reads it from a saved file, and it's cheap to
  // regenerate via a real recalculate if it's ever needed), so it isn't guaranteed to be here
  // even when the rest of results is.
  results?: Omit<RotationResults, 'dmgOverTimeSeries'>;
}

export class DataLoaderClass {
  cache = { mechanics: new Set<string>() };
  // Content-hash manifest (public/data/manifest.json, regenerated by
  // scripts/generate-data-manifest.mjs on every build/dev start) -- lets the app cheaply detect
  // that a data file it already has cached has changed on the server without re-downloading the
  // file itself. See src/utils/dataFreshness.ts for the staleness checks built on top of this.
  manifest: Record<string, string> = {};
  // The manifest hash recorded for a relative data path at the moment it was last successfully
  // fetched -- compared against a fresh manifest to tell "changed since loaded" apart from
  // "never loaded" or "unchanged".
  loadedHashes: Record<string, string> = {};
  private manifestFetchedAt = 0;
  characterDB: Record<string, CharacterData> = {};
  weaponDB: Record<string, WeaponData> = {};
  buildDB: Record<string, any> = {};
  mechanicsDB: Record<string, MechanicNode> = {};
  mechanicsIndex: Record<string, string[]> = {};
  charList: string[] = [];
  // Submitted rotation results for the Rankings page, keyed by filename -- loaded lazily (see
  // loadCharacterResults below), not as part of initDatabases, since unlike the four fixed
  // db_*.json files this folder is expected to grow and only the Rankings page needs it.
  characterResults: Record<string, CharacterResultData> = {};
  weaponsByType: Record<string, string[]> = {
    Broadblade: [], Sword: [], Rectifier: [], Gauntlets: [], Pistols: []
  };

  sonataSets: string[] = [];
  setEchoMapping: Record<string, string[]> = {};
  allMainEchoes: string[] = [];
  triggerSets: string[] = [];

  async loadJSON<T>(path: string, opts: { skipHashTracking?: boolean } = {}): Promise<T | null> {
    try {
      const res = await fetch(`${path}?t=${new Date().getTime()}`);
      if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
      const data = await res.json();
      // Record this path's *current* manifest hash (if we have one) as "what we just loaded" --
      // not the hash of `data` itself, since that would just tautologically always match.
      if (!opts.skipHashTracking) {
        const relPath = path.replace(/^\/data\//, '');
        if (this.manifest[relPath]) this.loadedHashes[relPath] = this.manifest[relPath];
      }
      return data;
    } catch (e) {
      console.error(`[DataLoader] Failed to load JSON from ${path}.`, e);
      return null;
    }
  }

  // The on-disk filename for a mechanic entity. Every part of this app *except* the actual file
  // on disk refers to the Generic/System entity as 'Generic' (nodeIdPrefix, the Builder's own
  // grid entry, clearMechanicCache's mechanicsDB/-Index special cases, etc.) -- the real file is
  // lowercase mechanics/generic/generic.json (see initDatabases' own loadMechanic call), so this
  // is the one place that has to know to translate between the two, rather than each caller
  // remembering to (or, worse, not remembering to -- a mismatched key here is exactly what let
  // Reset Cache on Generic silently fail to restore anything: clearMechanicCache evicted the
  // wrong cache-Set key, so the re-fetch right after it saw a cache "hit" and skipped entirely).
  private mechanicFileName(itemName: string): string {
    return itemName === 'Generic' ? 'generic' : itemName.replace(/\s+/g, '_');
  }

  // Same relPath -> URL convention loadMechanic uses internally, exposed so callers
  // (dataFreshness.ts) can ask "what path would loadMechanic use for this (folder,itemName)"
  // without duplicating the filename rule.
  mechanicPath(folder: string, itemName: string): string {
    return `mechanics/${folder}/${this.mechanicFileName(itemName)}.json`;
  }

  // Throttled (5s) so a burst of near-simultaneous callers (tab-focus + an in-flight Calculate,
  // say) collapses into one network request instead of one each. `force` bypasses the throttle
  // for the one startup call in initDatabases.
  async refreshManifest(force = false): Promise<Record<string, string>> {
    const now = Date.now();
    if (!force && this.manifestFetchedAt && now - this.manifestFetchedAt < 5000) return this.manifest;
    this.manifestFetchedAt = now;
    const fresh = await this.loadJSON<Record<string, string>>(CommonUtils.getData('manifest.json'), { skipHashTracking: true });
    if (fresh) {
      this.manifest = fresh;
      this.backfillLoadedHashes(fresh);
    }
    return this.manifest;
  }

  // Establishes a loadedHashes baseline for anything already in cache.mechanics that doesn't
  // have one yet -- covers entities whose very first fetch raced ahead of any manifest ever
  // being available (notably useRosterStore's persisted-team rehydration, which calls
  // loadMechanic directly from a zustand onRehydrateStorage callback that fires at module-init
  // time, before App's initDatabases -- and this call's very first refreshManifest -- has even
  // started). Runs on every successful manifest fetch, not just the first, so a path that's
  // *still* unhashed after one race gets another chance the next time anything refreshes the
  // manifest, rather than being stuck for the rest of the session.
  private backfillLoadedHashes(manifest: Record<string, string>): void {
    for (const cacheKey of this.cache.mechanics) {
      const relPath = `mechanics/${cacheKey}.json`;
      if (!this.loadedHashes[relPath] && manifest[relPath]) {
        this.loadedHashes[relPath] = manifest[relPath];
      }
    }
  }

  async initDatabases(): Promise<void> {
    await this.refreshManifest(true);
    this.characterDB = await this.loadJSON<Record<string, CharacterData>>(CommonUtils.getData('db_characters.json')) || {};
    this.weaponDB = await this.loadJSON<Record<string, WeaponData>>(CommonUtils.getData('db_weapons.json')) || {};
    this.buildDB = await this.loadJSON<Record<string, any>>(CommonUtils.getData('db_builds.json')) || {};

    this.charList = Object.keys(this.characterDB);
    this.weaponsByType = { Broadblade: [], Sword: [], Rectifier: [], Gauntlets: [], Pistols: [] };

    Object.keys(this.weaponDB).forEach(weaponName => {
      const type = this.weaponDB[weaponName].weaponType;
      if (this.weaponsByType[type]) this.weaponsByType[type].push(weaponName);
    });

    const echoData = await this.loadJSON<any>(CommonUtils.getData('db_echoes.json')) || {};
    this.setEchoMapping = echoData.SET_ECHO_MAPPING || {};
    this.sonataSets = Object.keys(this.setEchoMapping);
    this.allMainEchoes = Array.from(new Set(Object.values(this.setEchoMapping).flat()));
    this.triggerSets = echoData.TRIGGER_SETS || [];

    await this.loadMechanic('generic', 'generic');
  }

  // Loads every mechanic a team composition needs (each slot's character/weapon/sets/echo) --
  // shared by the roster store (main thread) and the calc worker, which has its own separate
  // DataLoader instance and so can't just read what the main thread already loaded.
  async loadTeamMechanics(team: Array<{ character?: string; weapon?: string; mainSet?: string; subSet?: string; mainEcho?: string }>): Promise<void> {
    for (const slot of team) {
      if (slot.character) await this.loadMechanic('characters', slot.character);
      if (slot.weapon) await this.loadMechanic('weapons', slot.weapon);
      if (slot.mainSet) await this.loadMechanic('sets', slot.mainSet);
      if (slot.subSet) await this.loadMechanic('sets', slot.subSet);
      if (slot.mainEcho) await this.loadMechanic('echoes', slot.mainEcho);
    }
  }

  async loadMechanic(folder: string, itemName: string): Promise<void> {
    if (!itemName) return;
    const fileName = this.mechanicFileName(itemName);
    const cacheKey = `${folder}/${fileName}`;
    if (this.cache.mechanics.has(cacheKey)) return;
    const data = await this.loadJSON<Record<string, MechanicNode>>(CommonUtils.getData(`mechanics/${folder}/${fileName}.json`));
    if (data) {
      for (const [key, mechData] of Object.entries(data)) {
        this.mechanicsDB[key] = mechData;
        const indexKey = key.startsWith('System_') ? 'System' : key.split('_')[0];
        if (!this.mechanicsIndex[indexKey]) this.mechanicsIndex[indexKey] = [];
        if (!this.mechanicsIndex[indexKey].includes(key)) this.mechanicsIndex[indexKey].push(key);
      }
      this.cache.mechanics.add(cacheKey);
    }
  }

  // Loads every submitted rotation result for the Rankings page. There's no way to list a
  // public/ folder's contents at runtime, so a hand-maintained manifest (index.json, just an
  // array of filenames + an optional rotationType tag) stands in for directory listing --
  // same shape of problem loadMechanic solves for one named file, just batched over a manifest.
  // Cached by filename the same way loadMechanic caches by folder/itemName, so re-calling this
  // (e.g. re-mounting the Rankings page) doesn't re-fetch files already loaded.
  async loadCharacterResults(): Promise<string[]> {
    const manifest = await this.loadJSON<Array<{ file: string; rotationType?: 'linear' | 'quickswap' | null }>>(
      CommonUtils.getData('character_results/index.json')
    ) || [];
    for (const entry of manifest) {
      if (this.characterResults[entry.file]) continue;
      const data = await this.loadJSON<Omit<CharacterResultData, 'rotationType'>>(
        CommonUtils.getData(`character_results/${entry.file}`)
      );
      if (data) this.characterResults[entry.file] = { ...data, rotationType: entry.rotationType ?? null };
    }
    return Object.keys(this.characterResults);
  }

  clearMechanicCache(folder: string, itemName: string): void {
    if (!itemName) return;
    // mechanicFileName's Generic->'generic' translation matters here specifically: get this
    // cache-Set key wrong and this eviction silently misses the entry loadMechanic actually
    // inserted. Left un-evicted, the very next loadMechanic call (initDatabases, right after
    // this in useBuilderStore's resetCache) sees its cache-Set entry still present and skips
    // re-fetching entirely -- so mechanicsDB's System_* entries, wiped just below, never get
    // restored, instead of the pristine data resetCache is meant to restore.
    const cacheKey = `${folder}/${this.mechanicFileName(itemName)}`;

    // 1. Evict from cache Set so loadMechanic will re-fetch the JSON file
    this.cache.mechanics.delete(cacheKey);

    // 2. Remove modified in-memory keys
    Object.keys(this.mechanicsDB).forEach(key => {
      if (key.startsWith(itemName + '_') || (itemName === 'Generic' && key.startsWith('System_'))) {
        delete this.mechanicsDB[key];
      }
    });

    const indexKey = itemName === 'Generic' ? 'System' : itemName;
    delete this.mechanicsIndex[indexKey];
  }
}

export const DataLoader = new DataLoaderClass();